"""
Community feed service layer.
Handles posts, likes, saves, comments, and sidebar stats for the
communities feed. Mirrors the structure of resource_service.py:
permission checks first, then CRUD, then reactions/comments, then stats.
"""

import json
from datetime import datetime
from typing import Optional, List, Tuple

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_, or_, func

from ..database.models import (
    Posts, PostLikes, PostSaves, PostComments,
    Users, Groups, Resources, PostType,
)
from .group_service import is_user_in_group
from .group_service import is_user_in_group, get_group_members
from ..schemas.notifications import CreateNotificationRequest
from .notification_service import create_notification
# ============================================================================
# PERMISSION CHECKS
# ============================================================================

async def can_user_view_post(
    session: AsyncSession,
    user_id: str,
    post_id: int
) -> bool:
    post = await get_post_by_id(session, post_id)
    if not post or post.is_deleted:
        return False

    # Posts not tied to a group are visible to anyone (public feed)
    if post.group_id is None:
        return True

    return await is_user_in_group(session, user_id, post.group_id)


async def can_user_modify_post(
    session: AsyncSession,
    user_id: str,
    post_id: int
) -> bool:
    post = await get_post_by_id(session, post_id)
    if not post or post.is_deleted:
        return False

    return post.user_id == user_id

# --- Add to the PERMISSION CHECKS section, alongside can_user_modify_post ---

async def get_comment_by_id(
    session: AsyncSession,
    comment_id: int,
) -> Optional[PostComments]:
    result = await session.execute(
        select(PostComments).where(
            and_(PostComments.id == comment_id, PostComments.is_deleted == False)
        )
    )
    return result.scalars().first()


async def can_user_delete_comment(
    session: AsyncSession,
    user_id: str,
    comment_id: int,
) -> bool:
    """Mirrors can_user_modify_post: only the comment's author may delete it.
    (Extend this later if you want post owners / group moderators to also
    be able to delete comments on their own posts.)"""
    comment = await get_comment_by_id(session, comment_id)
    if not comment:
        return False
    return comment.user_id == user_id


# --- delete_comment already exists; just have it use get_comment_by_id
#     instead of re-querying, no functional change needed there ---


# ============================================================================
# HELPERS
# ============================================================================

async def get_post_by_id(
    session: AsyncSession,
    post_id: int
) -> Optional[Posts]:
    result = await session.execute(
        select(Posts).where(
            and_(Posts.id == post_id, Posts.is_deleted == False)
        )
    )
    return result.scalars().first()


async def _get_like(session: AsyncSession, user_id: str, post_id: int) -> Optional[PostLikes]:
    result = await session.execute(
        select(PostLikes).where(
            and_(PostLikes.user_id == user_id, PostLikes.post_id == post_id)
        )
    )
    return result.scalars().first()


async def _get_save(session: AsyncSession, user_id: str, post_id: int) -> Optional[PostSaves]:
    result = await session.execute(
        select(PostSaves).where(
            and_(PostSaves.user_id == user_id, PostSaves.post_id == post_id)
        )
    )
    return result.scalars().first()


# ============================================================================
# CREATE
# ============================================================================

async def create_post(
    session: AsyncSession,
    user_id: str,
    post_type: PostType,
    title: str,
    text: Optional[str] = None,
    group_id: Optional[int] = None,
    resource_id: Optional[int] = None,
    link_data: Optional[dict] = None,
) -> Posts:
    type_data = json.dumps(link_data) if link_data else None

    post = Posts(
        user_id=user_id,
        group_id=group_id,
        post_type=post_type,
        title=title,
        text=text,
        resource_id=resource_id,
        type_data=type_data,
        is_deleted=False,
    )
    session.add(post)
    await session.flush()  # get autogenerated id

    # Notify group members, same pattern as create_resource
    if group_id is not None:
        members = await get_group_members(session, group_id)
        author = await session.get(Users, user_id)
        author_name = author.username if author else "Someone"

        type_label = {
            PostType.RESOURCE: "resource",
            PostType.QUESTION: "question",
            PostType.LINK: "link",
            PostType.ASSIGNMENT: "assignment",
        }.get(post_type, "post")

        for member in members:
            if member[0].user_id != user_id:
                await create_notification(
                    CreateNotificationRequest(
                        user_id=member[0].user_id,
                        title="New Community Post",
                        message=f"{author_name} posted a new {type_label} in your group: \"{title}\"",
                        type="CommunityPostCreated",
                    ),
                    session,
                )
        print(f"Post created and notifications sent for group {group_id}")
    return post


# ============================================================================
# READ
# ============================================================================

async def get_posts(
    session: AsyncSession,
    post_type: Optional[PostType] = None,
    group_id: Optional[int] = None,
    search: Optional[str] = None,
    skip: int = 0,
    limit: int = 20,
) -> Tuple[List[Posts], int]:
    query = select(Posts).where(Posts.is_deleted == False)

    if post_type:
        query = query.where(Posts.post_type == post_type)
    if group_id:
        query = query.where(Posts.group_id == group_id)
    if search:
        pattern = f"%{search}%"
        query = query.where(or_(Posts.title.ilike(pattern), Posts.text.ilike(pattern)))

    count_query = select(func.count()).select_from(query.subquery())
    total_result = await session.execute(count_query)
    total = total_result.scalar_one()

    query = query.order_by(Posts.created_at.desc()).offset(skip).limit(limit)
    result = await session.execute(query)
    posts = result.scalars().all()

    return list(posts), total


async def get_post_reaction_state(
    session: AsyncSession,
    user_id: str,
    post_id: int,
) -> dict:
    """Returns whether current user liked/saved a post — used to build response DTOs."""
    liked = await _get_like(session, user_id, post_id) is not None
    saved = await _get_save(session, user_id, post_id) is not None
    return {"liked_by_me": liked, "saved_by_me": saved}


# ============================================================================
# UPDATE
# ============================================================================

async def update_post(
    session: AsyncSession,
    post_id: int,
    title: Optional[str] = None,
    text: Optional[str] = None,
) -> Optional[Posts]:
    post = await get_post_by_id(session, post_id)
    if not post:
        return None

    if title is not None:
        post.title = title
    if text is not None:
        post.text = text

    await session.flush()
    return post


# ============================================================================
# DELETE - soft delete
# ============================================================================

async def delete_post(
    session: AsyncSession,
    post_id: int
) -> bool:
    post = await get_post_by_id(session, post_id)
    if not post:
        return False

    post.is_deleted = True
    await session.flush()
    return True


# ============================================================================
# REACTIONS: like / save / share
# ============================================================================

async def toggle_like(
    session: AsyncSession,
    user_id: str,
    post_id: int,
) -> Tuple[bool, int]:
    """Returns (is_now_liked, new_like_count)."""
    post = await get_post_by_id(session, post_id)
    if not post:
        raise ValueError("Post not found")

    existing = await _get_like(session, user_id, post_id)

    if existing:
        await session.delete(existing)
        post.like_count = max(0, post.like_count - 1)
        active = False
    else:
        session.add(PostLikes(user_id=user_id, post_id=post_id))
        post.like_count += 1
        active = True

    await session.flush()
    return active, post.like_count


async def toggle_save(
    session: AsyncSession,
    user_id: str,
    post_id: int,
) -> Tuple[bool, int]:
    """Returns (is_now_saved, new_save_count)."""
    post = await get_post_by_id(session, post_id)
    if not post:
        raise ValueError("Post not found")

    existing = await _get_save(session, user_id, post_id)

    if existing:
        await session.delete(existing)
        post.save_count = max(0, post.save_count - 1)
        active = False
    else:
        session.add(PostSaves(user_id=user_id, post_id=post_id))
        post.save_count += 1
        active = True

    await session.flush()
    return active, post.save_count


async def increment_share_count(
    session: AsyncSession,
    post_id: int,
) -> int:
    post = await get_post_by_id(session, post_id)
    if not post:
        raise ValueError("Post not found")

    post.share_count += 1
    await session.flush()
    return post.share_count


# ============================================================================
# COMMENTS
# ============================================================================

async def get_post_comments(
    session: AsyncSession,
    post_id: int,
) -> List[PostComments]:
    """Returns ALL comments (top-level + replies) for a post, oldest first.
    Caller is responsible for nesting replies under their parent."""
    result = await session.execute(
        select(PostComments)
        .where(
            and_(
                PostComments.post_id == post_id,
                PostComments.is_deleted == False,
            )
        )
        .order_by(PostComments.created_at.asc())
    )
    return list(result.scalars().all())


async def add_comment(
    session: AsyncSession,
    post_id: int,
    user_id: str,
    text: str,
    parent_comment_id: Optional[int] = None,
) -> PostComments:
    post = await get_post_by_id(session, post_id)
    if not post:
        raise ValueError("Post not found")

    if parent_comment_id:
        parent_result = await session.execute(
            select(PostComments).where(PostComments.id == parent_comment_id)
        )
        parent = parent_result.scalars().first()
        if not parent or parent.post_id != post_id:
            raise ValueError("Parent comment not found")

    comment = PostComments(
        post_id=post_id,
        user_id=user_id,
        parent_comment_id=parent_comment_id,
        text=text,
    )
    session.add(comment)
    post.comment_count += 1

    await session.flush()
    return comment


async def delete_comment(
    session: AsyncSession,
    comment_id: int,
) -> bool:
    result = await session.execute(
        select(PostComments).where(PostComments.id == comment_id)
    )
    comment = result.scalars().first()
    if not comment or comment.is_deleted:
        return False

    comment.is_deleted = True

    post = await get_post_by_id(session, comment.post_id)
    if post:
        post.comment_count = max(0, post.comment_count - 1)

    await session.flush()
    return True


# ============================================================================
# SIDEBAR / STATS
# ============================================================================

async def get_recent_uploads(
    session: AsyncSession,
    limit: int = 5,
) -> List[Posts]:
    result = await session.execute(
        select(Posts)
        .where(
            and_(
                Posts.post_type == PostType.RESOURCE,
                Posts.is_deleted == False,
            )
        )
        .order_by(Posts.created_at.desc())
        .limit(limit)
    )
    return list(result.scalars().all())


async def get_top_contributors(
    session: AsyncSession,
    limit: int = 3,
) -> List[dict]:
    """
    Contributions = posts + comments per user, combined.
    Returns a list of {"user_id": ..., "contributions": ...} sorted desc.
    """
    post_counts_result = await session.execute(
        select(Posts.user_id, func.count())
        .where(Posts.is_deleted == False)
        .group_by(Posts.user_id)
    )
    post_counts = dict(post_counts_result.all())

    comment_counts_result = await session.execute(
        select(PostComments.user_id, func.count())
        .where(PostComments.is_deleted == False)
        .group_by(PostComments.user_id)
    )
    comment_counts = dict(comment_counts_result.all())

    totals: dict[str, int] = {}
    for uid, count in post_counts.items():
        totals[uid] = totals.get(uid, 0) + count
    for uid, count in comment_counts.items():
        totals[uid] = totals.get(uid, 0) + count

    ranked = sorted(totals.items(), key=lambda x: x[1], reverse=True)[:limit]
    return [{"user_id": uid, "contributions": count} for uid, count in ranked]